#!/usr/bin/env python3
import os
import subprocess
import time
import threading
from concurrent.futures import ThreadPoolExecutor

TRACKER_FILE = "/Users/satabarto/.gemini/antigravity-ide/brain/79605cb8-0acd-4af9-899c-1539591d949b/tracker_sheet.md"

folders = [
    'FLSTM_Classification_EPL_Median',
    'FLSTM_Classification_MackeyGlass_Median',
    'FLSTM_Classification_Sunspots_Median'
]

# State variables
total_tasks = 27
completed_tasks = 0
failed_tasks = 0
running_tasks = []
finished_results = []
lock = threading.Lock()
start_time = time.time()

def format_time(seconds):
    h = int(seconds // 3600)
    m = int((seconds % 3600) // 60)
    s = seconds % 60
    return f"{h}h {m}m {s:.0f}s"

def update_tracker():
    with lock:
        elapsed = format_time(time.time() - start_time)
        status_md = f"""# Median Lag=5 Execution Tracker

> [!WARNING]
> This is a live execution tracker. Do not edit this file manually.

## Progress Summary
- **Total Notebooks:** {total_tasks}
- **Completed:** {completed_tasks}
- **Failed:** {failed_tasks}
- **Pending/Running:** {total_tasks - completed_tasks - failed_tasks}
- **Total Elapsed Time:** {elapsed}

## Currently Running
"""
        if running_tasks:
            for t in running_tasks:
                status_md += f"- ⏳ `{t}`\n"
        else:
            status_md += "- *None*\n"

        status_md += "\n## Finished Results\n"
        if finished_results:
            for r in finished_results:
                status_md += f"- {r}\n"
        else:
            status_md += "- *None*\n"
            
        with open(TRACKER_FILE, 'w') as f:
            f.write(status_md)

def run_notebook(nb_path):
    global completed_tasks, failed_tasks
    
    with lock:
        running_tasks.append(nb_path)
    update_tracker()
    
    cmd = [
        'jupyter', 'nbconvert',
        '--to', 'notebook',
        '--execute',
        '--inplace',
        '--ExecutePreprocessor.timeout=-1',
        nb_path
    ]
    nb_start = time.time()
    result = subprocess.run(cmd, capture_output=True, text=True)
    nb_elapsed = time.time() - nb_start
    
    with lock:
        running_tasks.remove(nb_path)
        if result.returncode == 0:
            completed_tasks += 1
            finished_results.append(f"✅ `{nb_path}` completed in **{format_time(nb_elapsed)}**")
        else:
            failed_tasks += 1
            finished_results.append(f"❌ `{nb_path}` failed after **{format_time(nb_elapsed)}**")
    
    update_tracker()

def main():
    tasks = []
    for folder in folders:
        notebooks = sorted([f for f in os.listdir(folder) if f.endswith('.ipynb')])
        for nb in notebooks:
            tasks.append(os.path.join(folder, nb))
    
    update_tracker()
    
    with ThreadPoolExecutor(max_workers=3) as executor:
        executor.map(run_notebook, tasks)
        
    update_tracker()

if __name__ == '__main__':
    main()
